2022-07-05 10:21:44,096 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2022-07-05 10:21:44,099 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from C:\Users\Blaze Pro\AppData\Local\Programs\Python\Python310\lib\site-packages\instabot\bot\bot.py
2022-07-05 10:21:44,102 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2022-07-05 10:21:44,842 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [200]>
2022-07-05 10:21:45,918 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2022-07-05 10:21:46,455 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
2022-07-05 10:21:47,474 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [429]>
2022-07-05 10:21:47,475 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"Please wait a few minutes before you try again.","status":"fail"}'
2022-07-05 10:21:47,475 - instabot version: 0.117.0 (api) - ERROR - Request returns 429 error!
2022-07-05 10:21:47,477 - instabot version: 0.117.0 (api) - WARNING - That means 'too many requests'. I'll go to sleep for 5 minutes.
